"use client";

import { AppShell } from "@/components/compras/AppShell";
import { demoProcesses, money } from "@/lib/compras";
import { ArrowUpRight, BellRing, CalendarClock, CheckCircle2, ClipboardList, FileText, Plus, Search, Timer } from "lucide-react";
import Link from "next/link";

export default function ComprasPage() {
  return <AppShell><div className="daddus-page-heading daddus-page-heading-actions"><div><span className="daddus-overline">Operacao municipal</span><h2>Central do Setor de Compras</h2><p>Monitore solicitacoes, processos e prazos da prefeitura.</p></div><Link href="/painel/secretario/solicitacoes" className="daddus-primary-button"><Plus size={16} /> Nova solicitacao</Link></div><div className="daddus-notice"><BellRing size={19} /><div><strong>3 novas solicitacoes de orcamento</strong><span>Secretarias enviaram pedidos desde sua ultima visita.</span></div><Link href="#solicitacoes">Ver solicitacoes <ArrowUpRight size={15} /></Link></div><section className="daddus-metric-grid"><Metric icon={<ClipboardList />} label="Processos ativos" value="12" note="4 em fase de cotacao" /><Metric icon={<Timer />} label="Prazos nesta semana" value="05" note="2 vencem ate sexta" tone="warning" /><Metric icon={<FileText />} label="Solicitacoes recebidas" value="28" note="8 aguardam analise" /><Metric icon={<CheckCircle2 />} label="Valor estimado" value={money(284750)} note="Em processos abertos" /></section><div className="daddus-content-grid"><section className="daddus-table-card" id="solicitacoes"><div className="daddus-card-heading"><div><span className="daddus-overline">Acompanhamento</span><h3>Lista mestra de processos e lotes</h3></div><div className="daddus-search"><Search size={15} /><input placeholder="Buscar processo ou objeto" /></div></div><div className="daddus-table-wrap"><table className="daddus-table"><thead><tr><th>Nº Processo</th><th>Objeto</th><th>Prazo limite</th><th>Status</th><th>Acoes</th></tr></thead><tbody>{demoProcesses.map((process) => <tr key={process.id}><td><strong>PE {process.id}</strong><small>{process.requester}</small></td><td>{process.object}</td><td><span className="deadline"><CalendarClock size={14} /> {process.deadline}</span></td><td><span className={`daddus-status ${process.status === "Em cotacao" ? "blue" : process.status === "Aguardando aprovacao" ? "yellow" : "gray"}`}>{process.status}</span></td><td><Link href={`/painel/compras/processo/${process.id}`} className="daddus-row-action">Abrir <ArrowUpRight size={14} /></Link></td></tr>)}</tbody></table></div></section><section className="daddus-task-card"><div className="daddus-card-heading"><div><span className="daddus-overline">Minha agenda</span><h3>Tarefas pessoais</h3></div></div><Task title="Revisar cotacoes do PE 2026-0142" date="Hoje, 16:00" /><Task title="Solicitar proposta ao fornecedor" date="Amanha, 10:30" /><Task title="Conferir termo de referencia" date="28 ago" /><label className="daddus-notes"><span>Comentarios / notas do processo</span><textarea placeholder="Registre um acompanhamento interno..." /></label><button className="daddus-secondary-button">Salvar nota</button></section></div></AppShell>;
}

function Metric({ icon, label, value, note, tone = "" }: { icon: React.ReactNode; label: string; value: string; note: string; tone?: string }) { return <article className={`daddus-metric ${tone}`}><span className="daddus-metric-icon">{icon}</span><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function Task({ title, date }: { title: string; date: string }) { return <div className="daddus-task"><input type="checkbox" /><div><strong>{title}</strong><span><CalendarClock size={12} /> {date}</span></div></div>; }
