"use client";

import { AppShell } from "@/components/compras/AppShell";
import { CheckCircle2, Paperclip, Send } from "lucide-react";
import { FormEvent, useState } from "react";

export default function SolicitacoesPage() {
  const [submitted, setSubmitted] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await fetch("/api/solicitacoes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ objeto: data.get("objeto"), justificativa: data.get("justificativa"), secretaria: data.get("secretaria") }) }); event.currentTarget.reset(); setSubmitted(true); };
  return <AppShell role="Secretaria de Educacao"><div className="daddus-page-heading"><div><span className="daddus-overline">Secretaria de Educacao</span><h2>Solicitar abertura de compra</h2><p>Envie ao Setor de Compras as informacoes iniciais para abrir um novo processo.</p></div></div><div className="daddus-split-layout"><form className="daddus-form-card" onSubmit={submit}><div className="daddus-form-section"><div><h3>Nova solicitacao</h3><p>Descreva o que sua secretaria precisa contratar.</p></div><div className="daddus-form-grid single"><label>Secretaria<select name="secretaria" defaultValue="educacao"><option value="educacao">Educacao</option><option value="saude">Saude</option><option value="assistencia">Assistencia Social</option><option value="administracao">Administracao</option></select></label><label>Objeto da compra<textarea name="objeto" rows={3} placeholder="Ex.: Material escolar para o ano letivo de 2026" required /></label><label>Justificativa<textarea name="justificativa" rows={5} placeholder="Explique a necessidade e o interesse publico da compra." required /></label><label className="file-input"><Paperclip size={17} /> Termo de referencia (opcional)<input name="termo" type="file" accept=".pdf,.doc,.docx" /><small>PDF ou DOCX · ate 10 MB</small></label></div></div><div className="daddus-form-actions"><button className="daddus-primary-button" type="submit"><Send size={16} /> Enviar solicitacao</button></div></form><aside className="daddus-info-card"><span className="daddus-info-icon">i</span><h3>Como funciona?</h3><ol><li>Preencha objeto e justificativa.</li><li>Anexe o termo de referencia, se ja estiver pronto.</li><li>O comprador recebe uma notificacao e inicia a cotacao.</li></ol></aside></div>{submitted && <div className="daddus-toast"><CheckCircle2 size={17} /> Solicitacao enviada ao Setor de Compras.</div>}</AppShell>;
}
